// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitingMS.Data;

#nullable disable

namespace VisitingMS.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230803054455_AddUserTableToDb")]
    partial class AddUserTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitingMS.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            DepartmentName = "Electrical",
                            HOD = "Mushaaf"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentName = "Mechenical",
                            HOD = "Haide"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentName = "Computing",
                            HOD = "Mushara"
                        });
                });

            modelBuilder.Entity("VisitingMS.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CNIC")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EntryTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNo")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitingPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorBelongings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNIC = 1234567890123L,
                            EntryTime = new DateTime(2023, 8, 3, 10, 44, 55, 701, DateTimeKind.Local).AddTicks(430),
                            FullName = "John Doe",
                            PhoneNo = 98765432101L,
                            VisitingPurpose = "Meeting",
                            VisitorBelongings = "Laptop, Bag"
                        },
                        new
                        {
                            Id = 2,
                            CNIC = 9876543210987L,
                            EntryTime = new DateTime(2023, 8, 3, 10, 44, 55, 701, DateTimeKind.Local).AddTicks(472),
                            FullName = "Jane Smith",
                            PhoneNo = 12345678901L,
                            VisitingPurpose = "Interview",
                            VisitorBelongings = "Mobile Phone"
                        },
                        new
                        {
                            Id = 3,
                            CNIC = 5555555555555L,
                            EntryTime = new DateTime(2023, 8, 3, 10, 44, 55, 701, DateTimeKind.Local).AddTicks(488),
                            FullName = "Michael Johnson",
                            PhoneNo = 11111111111L,
                            VisitingPurpose = "Training",
                            VisitorBelongings = "Backpack"
                        },
                        new
                        {
                            Id = 4,
                            CNIC = 9999999999999L,
                            EntryTime = new DateTime(2023, 8, 3, 10, 44, 55, 701, DateTimeKind.Local).AddTicks(504),
                            FullName = "Emily Wilson",
                            PhoneNo = 22222222222L,
                            VisitingPurpose = "Delivery",
                            VisitorBelongings = "None"
                        },
                        new
                        {
                            Id = 5,
                            CNIC = 4444444444444L,
                            EntryTime = new DateTime(2023, 8, 3, 10, 44, 55, 701, DateTimeKind.Local).AddTicks(520),
                            FullName = "David Lee",
                            PhoneNo = 33333333333L,
                            VisitingPurpose = "Maintenance",
                            VisitorBelongings = "Keys"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
